re-wrote the loader build process

diff --git a/scripts/bld-loader.sh.in b/scripts/bld-loader.sh.in
--- a/scripts/bld-loader.sh.in
+++ b/scripts/bld-loader.sh.in
@@ -45,6 +45,70 @@ cl_libdir="@@CL_LIBDIR@@"
 
 # *************************************************************************** #
 #                                                                             #
+# F U N C T I O N S                                                           #
+#                                                                             #
+# *************************************************************************** #
+
+
+# *****************************************************************************
+# Cleanup any built and in-progress loader build.
+# *****************************************************************************
+
+loader_clean() {
+
+echo "=> Removing the loader:"
+rm --verbose --force --recursive "${TARGET_LOADER_DIR}/"*
+
+}
+
+
+# *****************************************************************************
+# Build a loader package from source.
+# *****************************************************************************
+
+# Function Arguments:
+#      $1 ... Package name, like "glibc-2.19".
+
+loader_xbuild() {
+
+unset pkg_patch
+unset pkg_configure
+unset pkg_make
+unset pkg_install
+unset pkg_clean
+source "${CROSSLINUX_LOADER_DIR}/$1/bld.sh"
+
+# Get the source package.  This function will unzip and untar the source
+# package.
+#
+echo -n "i> Getting loader source package ... "
+CL_package_get ${PKG_ZIP}
+echo    "DONE"
+
+# Patch, configure, and build.
+#
+PKG_STATUS=""
+[[ -z "${PKG_STATUS}" ]] && pkg_patch     $1
+[[ -z "${PKG_STATUS}" ]] && pkg_configure $1
+[[ -z "${PKG_STATUS}" ]] && pkg_make      $1
+[[ -z "${PKG_STATUS}" ]] && pkg_install   $1
+[[ -z "${PKG_STATUS}" ]] && pkg_clean     $1
+if [[ -n "${PKG_STATUS}" ]]; then
+	echo -e "${TEXT_BRED}ERROR${TEXT_NORM}" >&${CONSOLE_FD}
+	echo    "E> ${PKG_STATUS}"              >&${CONSOLE_FD}
+	exit 1 # Bust out of sub-shell.
+fi
+unset PKG_STATUS
+
+# Remove the un-tarred loader source package directory.
+#
+[[ -d "${PKG_DIR}" ]] && rm --force --recursive "${PKG_DIR}" || true
+
+}
+
+
+# *************************************************************************** #
+#                                                                             #
 # M A I N   P R O G R A M                                                     #
 #                                                                             #
 # *************************************************************************** #
@@ -53,6 +117,10 @@ cl_libdir="@@CL_LIBDIR@@"
 # *****************************************************************************
 # Set up the shell functions and environment variables.
 # *****************************************************************************
+
+declare K_LOADER=""
+
+K_LDRLIST="crosslinux-loader.txt"
 
 source ./crosslinux-config.sh # target build configuration
 source ${cl_libdir}/scripts/_constants.sh # build support
@@ -71,7 +139,37 @@ CL_config_setup || exit 1
 #                      in-progress loader build artifacts, maybe leftover from
 #                      loader build problem.
 
-pushd "${TARGET_BUILD_DIR}/loader" >/dev/null 2>&1
+if [[ $# -gt 0 && -n "$1" ]]; then
+	# "$1" may be unbound so hide it in this if statement.
+	# Clean if so asked.
+	if [[ "$1" == "clean" ]]; then
+		loader_clean
+		exit 0
+	fi
+fi
+
+_c=0  # Package count.
+
+# Need to get the loader package from the ${K_LDRLIST} file.
+while read pname pad; do
+	[[ -z "${pname}"         ]] && continue || true
+	[[ "${pname:0:1}" == "#" ]] && continue || true
+	K_LOADER=${pname}
+	_c=$((${_c} + 1))
+done <${K_LDRLIST}
+
+unset _c
+
+if [[ -z "${K_LOADER}" ]]; then
+	echo "E> No loader package to build.  How did you do that?"
+	exit 1
+fi
+
+# -----------------------------------------------------------------------------
+# Build Loader
+# -----------------------------------------------------------------------------
+
+pushd "${TARGET_LOADER_DIR}" >/dev/null 2>&1
 
 # Even with 'set +e' the trap handler will run if a command or shell function
 # returns non-zero, and in that case the trap handler also will run when the
@@ -88,7 +186,7 @@ CL_exitOnSigErr=0
 # print a backtrace for the subshell, if a command or shell function returns
 # non-zero.
 CL_infoOnSigErr=1
-source "${CROSSLINUX_LOADER_DIR}/bld.sh" "${1:-}"
+loader_xbuild "${K_LOADER}"
 )
 set -e ; # All done with build steps; enable exit on a non-zero status.
 CL_infoOnSigErr=1
