simplify and take away some coupling

diff --git a/scripts/bld-kernel.sh.in b/scripts/bld-kernel.sh.in
--- a/scripts/bld-kernel.sh.in
+++ b/scripts/bld-kernel.sh.in
@@ -51,6 +51,34 @@ cl_libdir="@@CL_LIBDIR@@"
 
 
 # *****************************************************************************
+# Cleanup any built and in-progress kernel build.
+# *****************************************************************************
+
+kernel_clean() {
+
+echo "=> Removing kernel modules package, if any."
+rm --force --recursive "${TARGET_BUILD_DIR}/kpkgs/"*
+
+echo "=> Removing kernel and module tree, if any."
+rm --force --recursive "${TARGET_BUILD_DIR}/kroot/"*
+
+echo "=> Removing kernel source tree, if any."
+rm --force --recursive "${TARGET_BUILD_DIR}/linux-"*
+
+echo "=> Removing kernel build log, if any."
+for _file in ${TARGET_VAR_DIR}/log/*; do
+	[[ ! -f "${_file}" ]] && continue || true
+	if [[ ${_file##*/} =~ ^linux- ]]; then
+		echo "   -> ${_file##*/}."
+		rm --force ${_file}
+	fi
+done
+unset _file
+
+}
+
+
+# *****************************************************************************
 # Find the Linux kernel source package.
 # *****************************************************************************
 
@@ -408,7 +436,7 @@ return 0
 # Clean stuffs.
 # *****************************************************************************
 
-kernel_clean() {
+kernel_cleanup() {
 
 echo -n "c" >&${CONSOLE_FD}
 
@@ -448,6 +476,21 @@ CL_config_setup || exit 1
 # *****************************************************************************
 # Main Program
 # *****************************************************************************
+
+# Check for a script argument:
+#
+# $1 == "clean" ...... This means to clean any kernel build artifacts and any
+#                      in-progress kernel build artifacts, maybe leftover from
+#                      kernel build problem.
+
+if [[ $# -gt 0 && -n "$1" ]]; then
+	# "$1" may be unbound so hide it in this if statement.
+	# Clean if so asked.
+	if [[ "$1" == "clean" ]]; then
+		kernel_clean
+		exit 0
+	fi
+fi
 
 echo ""
 echo "##### START cross-building the kernel"
@@ -497,7 +540,7 @@ rm --force "${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log"
 kernel_src_get >>"${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log" 2>&1
 kernel_xbuild  >>"${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log" 2>&1
 kernel_collect >>"${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log" 2>&1
-kernel_clean   >>"${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log" 2>&1
+kernel_cleanup >>"${TARGET_VAR_DIR}/log/${K_KERNEL_SOURCE_NAME}.log" 2>&1
 )
 if [[ $? -ne 0 ]]; then
 	echo -e "${TEXT_BRED}ERROR${TEXT_NORM}"
diff --git a/scripts/bld-pkgs.sh.in b/scripts/bld-pkgs.sh.in
--- a/scripts/bld-pkgs.sh.in
+++ b/scripts/bld-pkgs.sh.in
@@ -51,13 +51,48 @@ cl_libdir="@@CL_LIBDIR@@"
 
 
 # *****************************************************************************
+# Cleanup any built and in-progress package build.
+# *****************************************************************************
+
+package_clean() {
+
+echo "=> Removing the packages:"
+
+echo "   -> Removing build/pkgs contents."
+rm --force --recursive "${TARGET_BUILD_DIR}/pkgs/"*
+
+echo "   -> Removing sysroot contents."
+rm --force --recursive "${TARGET_SYSROOT_DIR}/"*
+
+echo "   -> Removing pkg-bin/ binary packages."
+rm --force --recursive "${TARGET_PKGBIN_DIR}/"*
+
+echo "   -> Removing var/log/ build logs."
+for _file in "${TARGET_VAR_DIR}/log/"*; do
+	[[ ! -f "${_file}" ]] && continue || true
+	if [[ ${_file##*/} =~ ^linux- ]]; then
+		:
+	else
+		echo "   -> ... ${_file##*/}."
+		rm --force ${_file}
+	fi
+done
+
+echo "   -> Removing var/run/done.* build flags."
+rm --force --recursive ${TARGET_VAR_DIR}/run/done.*
+unset _file
+
+}
+
+
+# *****************************************************************************
 # Build a package from source.
 # *****************************************************************************
 
 # Function Arguments:
 #      $1 ... Package name, like "glibc-2.19".
 
-pkg_xbuild() {
+package_xbuild() {
 
 echo -n "g." >&${CONSOLE_FD}
 
@@ -86,7 +121,7 @@ fi
 #			NOTE -- Post-configuration patches might be applied.
 #
 #	pkg_make	This function builds the source package in place in the
-#			${TARGET_BUILD_DIR}/packages/ directory
+#			${TARGET_BUILD_DIR}/pkgs/ directory
 #
 #	pkg_install	This function installs any built items into the build
 #			root ${TARGET_SYSROOT_DIR}/ directory tree.
@@ -178,6 +213,10 @@ CL_config_setup || exit 1
 # $1 == "continue" ... This is a continuation flag, start making packages after
 #                      the last one previously made.
 #
+# $1 == "clean" ...... This means to clean any package build artifacts and any
+#                      in-progress package build artifacts, maybe leftover from
+#                      package build problem.
+#
 # $1 == <name> ....... Anything other than "continue" is interpreted as a
 #                      package name, so build the one named package.
 
@@ -186,7 +225,12 @@ _p="" # Package name.
 
 if [[ $# -gt 0 && -n "$1" ]]; then
 	# "$1" may be unbound so hide it in this if statement.
-	# Set the K_ZIPP flag, if so given; otherwise reset the package list.
+	# Clean if so asked. Otherwise set the K_ZIPP flag, if so given;
+	# otherwise reset the package list.
+	if [[ "$1" == "clean" ]]; then
+		package_clean
+		exit 0
+	fi
 	[[ "$1" == "continue" ]] && K_ZIPP="y" || _p=$1
 fi
 
@@ -226,10 +270,10 @@ echo "m_xxx. - looking for man pages to compress"
 echo "p.     - creating installable package"
 echo ""
 
-pushd "${TARGET_BUILD_DIR}/packages" >/dev/null 2>&1
+pushd "${TARGET_BUILD_DIR}/pkgs" >/dev/null 2>&1
 
 if [[ $(ls -1 | wc -l) -ne 0 ]]; then
-	echo "w> build/packages build directory is not empty:"
+	echo "w> build/pkgs build directory is not empty:"
 	ls -l
 	echo ""
 fi
@@ -272,7 +316,7 @@ for p in ${K_PACKAGE[@]}; do
 	# function returns non-zero.
 	CL_infoOnSigErr=1
 	rm --force "${TARGET_VAR_DIR}/log/${p}.log"
-	pkg_xbuild "${p}" >>"${TARGET_VAR_DIR}/log/${p}.log" 2>&1
+	package_xbuild "${p}" >>"${TARGET_VAR_DIR}/log/${p}.log" 2>&1
 	fakeroot -- "${CROSSLINUX_SCRIPT_DIR}/bld-pkgs-install.sh" "${p}" \
 					>>"${TARGET_VAR_DIR}/log/${p}.log" 2>&1
 	pkg_clean
@@ -301,7 +345,7 @@ for p in ${K_PACKAGE[@]}; do
 	echo "]"
 
 	if [[ $(ls -1 | wc -l) -ne 0 ]]; then
-		echo "w> build/packages build directory is not empty:"
+		echo "w> build/pkgs build directory is not empty:"
 		ls -l
 	fi
 
