added pkg-cfg filelist interpreter; unified pkg-cfg libc

diff --git a/scripts/bld-packages.sh.in b/scripts/bld-packages.sh.in
--- a/scripts/bld-packages.sh.in
+++ b/scripts/bld-packages.sh.in
@@ -51,13 +51,95 @@ cl_libdir="@@CL_LIBDIR@@"
 
 
 # *****************************************************************************
+# Make a file to list the package contents.
+# *****************************************************************************
+
+# Function Arguments:
+#      $1 ... ASCII file that is the file list
+
+package_list_make() {
+
+# The file list is an ASCII file that is the list of files from which to make
+# the binary package; it can have some scripting that interprets variables to
+# enable the selection of package files, so the file list needs some special
+# processing.  It is filtered, honoring any embedded scripting, and the actual
+# list of binary package files is created as ${TARGET_VAR_DIR}/files
+
+local cfgPkgFiles="$1"
+local pathname=""
+
+local -i lineNum=0
+local -i nestings=0
+local -i uselines=1
+local -i oldUseLine=1
+local -i retStat=0
+
+CL_logcom "***** Making Package File List"
+
+rm --force "${TARGET_VAR_DIR}/files"
+>"${TARGET_VAR_DIR}/files"
+while read; do
+	lineNum=$((${lineNum}+1))
+	if [[ "${REPLY}" =~ ^if\  ]]; then # ........ Interpret the 'if' lines.
+		if [[ ${nestings} == 1 ]]; then
+CL_logcom "E> Cannot nest scripting in pkg-cfg files-list file."
+CL_logcom "=> line ${lineNum}: \"${REPLY}\""
+			continue
+		fi
+		set ${REPLY}
+		if [[ $# != 4 ]]; then
+CL_logcom "E> IGNORING malformed script in pkg-cfg files-list file."
+CL_logcom "=> line ${lineNum}: \"${REPLY}\""
+			continue
+		fi
+		oldUseLine=${uselines}
+		eval [[ "\$$2" $3 "$4" ]] && uselines=1 || uselines=0
+		nestings=1
+CL_logcom "if \$$2 $3 $4 # -- nestings=${nestings} uselines=${uselines}"
+		continue
+	fi
+	if [[ "${REPLY}" =~ ^fi ]]; then # .......... Interpret the 'fi' lines.
+		uselines=${oldUseLine}
+		nestings=0
+CL_logcom "fi # ------------- nestings=${nestings} uselines=${uselines}"
+		continue
+	fi
+	if [[ "${REPLY}" =~ ^\ *# ]]; then # ..... Interpret the comment lines.
+CL_logcom "Skipping ${REPLY}"
+		continue
+	fi
+	if [[ ${uselines} == 1 ]]; then # ........... Interpret the used lines.
+		eval "pathname=${REPLY}"
+		echo ${pathname} >>"${TARGET_VAR_DIR}/files"
+	fi
+done <"${cfgPkgFiles}"
+
+while read; do
+	if [[ ! -e ${TARGET_SYSROOT_DIR}/${REPLY} ]]; then
+		CL_logcom "ERROR ***** missing \"${REPLY}\""
+		CL_logcom "=> in ${cfgPkgFiles}"
+		retStat=1
+	fi
+done <"${TARGET_VAR_DIR}/files"
+
+if [[ ${retStat} -eq 1 ]]; then
+	echo -e "${TEXT_BRED}ERROR${TEXT_NORM}"         >&${CONSOLE_FD}
+	echo    "E> Something wrong in ${cfgPkgFiles}." >&${CONSOLE_FD}
+fi
+
+return ${retStat}
+
+}
+
+
+# *****************************************************************************
 # Build a package from source and install into the sysroot.
 # *****************************************************************************
 
-package_xbuild() {
-
 # Function Arguments:
 #      $1 ... Package name, like "glibc-2.19".
+
+package_xbuild() {
 
 echo -n "g." >&${CONSOLE_FD}
 
@@ -129,6 +211,14 @@ source "${CROSSLINUX_PKGCFG_DIR}/$1/bld.sh"
 #
 [[ "x${PKG_ZIP}" == "x(none)" ]] || CL_package_get ${PKG_ZIP}
 
+# Prepare to create a list of the installed files.
+#
+rm --force INSTALL_STAMP
+rm --force FILES
+>INSTALL_STAMP
+>FILES
+sleep 1 # For detecting files newer than INSTALL_STAMP
+
 # Figure the number of parallel jobs to give to make.
 #
 _bitch=${K_NCPU:-1}
@@ -147,10 +237,10 @@ echo -n "b." >&${CONSOLE_FD}
 [[ -z "${PKG_STATUS}" ]] && pkg_clean     $1
 unset NJOBS
 if [[ -n "${PKG_STATUS}" ]]; then
-        CL_logcom "ERROR ***** ${PKG_STATUS}"
-        echo -e "${TEXT_BRED}ERROR${TEXT_NORM}" >&${CONSOLE_FD}
-        echo    "E> ${PKG_STATUS}"              >&${CONSOLE_FD}
-        exit 1 # Bust out of sub-shell.
+	CL_logcom "ERROR ***** ${PKG_STATUS}"
+	echo -e "${TEXT_BRED}ERROR${TEXT_NORM}" >&${CONSOLE_FD}
+	echo    "E> ${PKG_STATUS}"              >&${CONSOLE_FD}
+	exit 1 # Bust out of sub-shell.
 fi
 unset PKG_STATUS
 
@@ -164,6 +254,15 @@ rm --force ${TARGET_SYSROOT_DIR}/usr/lib/*.la
 #
 [[ -d "${PKG_DIR}" ]] && rm --force --recursive "${PKG_DIR}" || true
 [[ -d "rootfs"     ]] && rm --force --recursive "rootfs"     || true
+
+# Make a list of the installed files.  Remove sysroot and its path component
+# from the file names.
+#
+echo -n "f." >&${CONSOLE_FD}
+${cl_find} ${TARGET_SYSROOT_DIR} -newer INSTALL_STAMP | sort >> FILES
+${cl_sed} --in-place "FILES" --expression="\#^${TARGET_SYSROOT_DIR}\$#d"
+${cl_sed} --in-place "FILES" --expression="s|^${TARGET_SYSROOT_DIR}/||"
+rm --force INSTALL_STAMP # All done with the INSTALL_STAMP file.
 
 ## Strip when possible.
 ##
@@ -226,7 +325,64 @@ manpage_compress() {
 # *****************************************************************************
 
 package_collect() {
-:
+
+echo -n "p." >&${CONSOLE_FD}
+
+local fileList=""
+local shareDir="${TARGET_SYSROOT_DIR}/usr/share/${CONFIG_BRAND_NAME}"
+
+# Save the list of files actually installed into sysroot/
+#
+cp --force FILES "${shareDir}/pkg-$1-FILES"
+rm --force FILES # All done with the FILES file.
+
+# Look for a package configuration file list.  There does not need to be one.
+#
+_fname1="${CROSSLINUX_PKGCFG_DIR}/$1/files"
+_fname2="site/pkg-cfg-$1/files"
+if [[ -f "${_fname1}" ]]; then
+	fileList="${_fname1}"
+fi
+if [[ -f "${_fname1}-${CONFIG_CPU_ARCH}" ]]; then
+	fileList="${_fname1}-${CONFIG_CPU_ARCH}"
+fi
+if [[ -f "${_fname2}" ]]; then
+	fileList="${_fname2}"
+fi
+if [[ -f "${_fname2}-${CONFIG_CPU_ARCH}" ]]; then
+	fileList="${_fname2}-${CONFIG_CPU_ARCH}"
+fi
+unset _fname1
+unset _fname2
+
+if [[ -z "${fileList}" ]]; then
+	CL_logcom "ERROR ***** No file list for package $1."
+	echo -e "${TEXT_BRED}ERROR${TEXT_NORM}"  >&${CONSOLE_FD}
+	echo "E> No file list for package $1."   >&${CONSOLE_FD}
+	exit 1
+fi
+
+# This is tricky.  First make a ${TARGET_VAR_DIR}/files from ${fileList}; then
+# make a binary package from the list in ${TARGET_VAR_DIR}/files
+#
+package_list_make "${fileList}" || exit 1 # Bust out of sub-shell.
+_uTarBall="${TARGET_PKGBIN_DIR}/$1-${CONFIG_CPU_ARCH}.tar"
+_cTarBall="${TARGET_PKGBIN_DIR}/$1-${CONFIG_CPU_ARCH}.tbz"
+${cl_tar} --create \
+	--directory="${TARGET_SYSROOT_DIR}" \
+	--file="${_uTarBall}" \
+	--files-from="${TARGET_VAR_DIR}/files" \
+	--no-recursion
+${cl_bzip2} --force "${_uTarBall}"
+mv --force "${_uTarBall}.bz2" "${_cTarBall}"
+unset _uTarBall
+unset _cTarBall
+rm --force "${TARGET_VAR_DIR}/files" # Remove the temporary file.
+
+echo -n "c" >&${CONSOLE_FD}
+
+return 0
+
 }
 
 
@@ -375,7 +531,7 @@ for p in ${K_PACKAGE[@]}; do
 	exec >&4     # Set fd 1 back to stdout.
 	CONSOLE_FD=1 #
 
-	touch "${TARGET_VAR_DIR}/run/done.${p}"
+	>"${TARGET_VAR_DIR}/run/done.${p}"
 
 	echo -n " ... DONE ["
 	t2=${SECONDS}
